import { defineStore } from "pinia";

export const useTableStore = defineStore({
  id: "table",
  state: () => ({
    tables: [
      {
        name: "โต๊ะที่1",
        checkin: "13:00",
        checkout: "",
        total: 299,
        users: 5,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่2",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่3",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่4",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่5",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่6",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่7",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่8",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่9",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
      {
        name: "โต๊ะที่10",
        checkin: "",
        checkout: "",
        total: 0,
        users: 0,
        status: "ready",
        foods: [],
      },
    ],
  }),
  actions: {},
});
